-- SwasthTrack database schema: SUPERSEDED. This file intentionally contains no SQL.
--
-- The schema is defined by the migrations in supabase/migrations/. Run them in
-- the Supabase SQL editor, in this order, each once (they are written to be safe
-- to re-run):
--
--   1. supabase/migrations/20260823000000_phase2_schema.sql
--   2. supabase/migrations/20260824000000_phase3_food_schema.sql
--   3. supabase/migrations/20260828000000_ask_mode_schema.sql
--   4. supabase/migrations/20261004000000_secure_auth_rls_soie.sql
--
-- WHY THIS FILE WAS EMPTIED
--   The previous copy of this file created tables and then granted every
--   operation to the "anon" and "authenticated" roles with "USING (true)"
--   policies, and seeded demo patient data. That meant anyone holding the public
--   anon key could read and change every family's health records. Those
--   permissive anon policies were removed on purpose. Do not bring them back.
--
-- WHAT REPLACED THEM
--   Migration 4 adds real accounts (profiles), patient membership with roles
--   (patient_members: owner / editor / viewer), caregiver invite codes, and
--   Row Level Security on every table. The anon role has no table access.
--
-- SETTING UP A NEW ENVIRONMENT
--   1. Run the four migrations above, in order.
--   2. Follow docs/auth-setup.md: Supabase Auth settings (email provider,
--      confirm email, custom SMTP, 6-digit OTP), the email templates in
--      supabase/email-templates/, URL configuration, environment variables,
--      and (only if you already have patient data) supabase/scripts/
--      link_existing_patient.sql.
--   3. See docs/deployment.md for Vercel and the post-deploy checklist.
