-- SwasthTrack: complete MySQL schema (replaces supabase/migrations/*).
--
-- Works on MySQL 5.7 and 8.x (and TiDB / MariaDB-compatible hosts): no expression
-- defaults, no partial indexes, no CTEs. IDEMPOTENT: every statement is
-- CREATE TABLE IF NOT EXISTS, so running it twice is safe.
--
--   node scripts/db/migrate.mjs            # applies this file to DATABASE_URL
--
-- Conventions
--   * ids are CHAR(36) UUIDs generated by the app (crypto.randomUUID()).
--   * every DATETIME(3) holds UTC. The app sets `time_zone = '+00:00'` on each
--     connection, so CURRENT_TIMESTAMP(3) defaults are UTC too.
--   * JSON columns cannot carry a default in MySQL 5.7, so the app supplies them
--     (see src/lib/db/schema.ts `defaults`).
--   * Who may read or write which row is enforced in the server (src/lib/db/executor.ts),
--     not in the database: the browser never talks to MySQL.
--   * CHECK constraints are enforced on MySQL 8.0.16+ and parsed-but-ignored on 5.7.

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- 1. Accounts, sessions, one-time codes
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS auth_users (
  id                CHAR(36) CHARACTER SET ascii NOT NULL,
  email             VARCHAR(254) NOT NULL,
  password_hash     VARCHAR(255) NOT NULL,
  email_verified_at DATETIME(3) NULL,
  last_sign_in_at   DATETIME(3) NULL,
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_auth_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS profiles (
  id           CHAR(36) CHARACTER SET ascii NOT NULL,
  email        VARCHAR(254) NULL,
  display_name VARCHAR(120) NULL,
  role         VARCHAR(10) NOT NULL DEFAULT 'member',
  created_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT fk_profiles_user FOREIGN KEY (id) REFERENCES auth_users (id) ON DELETE CASCADE,
  CONSTRAINT ck_profiles_role CHECK (role IN ('member', 'admin'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Only a SHA-256 of the session token is stored; the token itself lives in the
-- browser's HttpOnly cookie.
CREATE TABLE IF NOT EXISTS auth_sessions (
  id           CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id      CHAR(36) CHARACTER SET ascii NOT NULL,
  token_hash   CHAR(64) CHARACTER SET ascii NOT NULL,
  user_agent   VARCHAR(255) NULL,
  created_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_seen_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  expires_at   DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_auth_sessions_token (token_hash),
  KEY idx_auth_sessions_user (user_id),
  KEY idx_auth_sessions_expiry (expires_at),
  CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6-digit e-mail codes. Only an HMAC of the code is stored.
--   purpose: signup (verify a new address) | login (passwordless) | recovery (password reset)
CREATE TABLE IF NOT EXISTS auth_otps (
  id          CHAR(36) CHARACTER SET ascii NOT NULL,
  email       VARCHAR(254) NOT NULL,
  purpose     VARCHAR(10) NOT NULL,
  code_hash   CHAR(64) CHARACTER SET ascii NOT NULL,
  attempts    INT NOT NULL DEFAULT 0,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  expires_at  DATETIME(3) NOT NULL,
  consumed_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_auth_otps_lookup (email, purpose, created_at),
  CONSTRAINT ck_auth_otps_purpose CHECK (purpose IN ('signup', 'login', 'recovery'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Counters for rate limiting (failed logins, code sends). `key_hash` is a SHA-256,
-- so no e-mail address or IP is stored here.
CREATE TABLE IF NOT EXISTS auth_attempts (
  id       BIGINT NOT NULL AUTO_INCREMENT,
  kind     VARCHAR(24) NOT NULL,
  key_hash CHAR(64) CHARACTER SET ascii NOT NULL,
  at       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_auth_attempts_lookup (kind, key_hash, at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- 2. Patients and their health records
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS patients (
  id                   CHAR(36) CHARACTER SET ascii NOT NULL,
  name                 VARCHAR(200) NOT NULL,
  age                  INT NULL,
  gender               VARCHAR(10) NULL,
  height_cm            DECIMAL(6,2) NULL,
  current_weight_kg    DECIMAL(6,2) NULL,
  target_weight_kg     DECIMAL(6,2) NULL,
  daily_calorie_target INT NULL DEFAULT 1600,
  created_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT ck_patients_age CHECK (age IS NULL OR (age > 0 AND age <= 120)),
  CONSTRAINT ck_patients_gender CHECK (gender IS NULL OR gender IN ('Male', 'Female', 'Other')),
  CONSTRAINT ck_patients_height CHECK (height_cm IS NULL OR height_cm > 0),
  CONSTRAINT ck_patients_weight CHECK (current_weight_kg IS NULL OR current_weight_kg > 0),
  CONSTRAINT ck_patients_target CHECK (target_weight_kg IS NULL OR target_weight_kg > 0),
  CONSTRAINT ck_patients_calories CHECK (daily_calorie_target IS NULL OR daily_calorie_target > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- owner  = manages caregivers, may delete the patient
-- editor = may log data
-- viewer = read-only
CREATE TABLE IF NOT EXISTS patient_members (
  id         CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id    CHAR(36) CHARACTER SET ascii NOT NULL,
  role       VARCHAR(10) NOT NULL,
  status     VARCHAR(10) NOT NULL DEFAULT 'active',
  invited_by CHAR(36) CHARACTER SET ascii NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_patient_members (patient_id, user_id),
  KEY idx_patient_members_user (user_id, status),
  KEY idx_patient_members_patient (patient_id, status),
  CONSTRAINT fk_pm_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT fk_pm_user FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE,
  CONSTRAINT fk_pm_invited_by FOREIGN KEY (invited_by) REFERENCES auth_users (id) ON DELETE SET NULL,
  CONSTRAINT ck_pm_role CHECK (role IN ('owner', 'editor', 'viewer')),
  CONSTRAINT ck_pm_status CHECK (status IN ('active', 'revoked'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS patient_settings (
  patient_id             CHAR(36) CHARACTER SET ascii NOT NULL,
  daily_calorie_target   INT NOT NULL DEFAULT 1600,
  daily_step_goal        INT NOT NULL DEFAULT 6000,
  sleep_target_hours     DECIMAL(4,2) NOT NULL DEFAULT 7,
  bp_monitoring_schedule VARCHAR(20) NOT NULL DEFAULT 'morning_evening',
  weight_unit            VARCHAR(4) NOT NULL DEFAULT 'kg',
  height_unit            VARCHAR(8) NOT NULL DEFAULT 'cm',
  distance_unit          VARCHAR(8) NOT NULL DEFAULT 'km',
  timezone               VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
  preferred_language     VARCHAR(12) NOT NULL DEFAULT 'bilingual',
  alerts_enabled         JSON NOT NULL,
  bp_targets             JSON NOT NULL,
  updated_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (patient_id),
  CONSTRAINT fk_ps_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT ck_ps_calories CHECK (daily_calorie_target > 0),
  CONSTRAINT ck_ps_steps CHECK (daily_step_goal > 0),
  CONSTRAINT ck_ps_sleep CHECK (sleep_target_hours > 0 AND sleep_target_hours <= 14),
  CONSTRAINT ck_ps_bp_schedule CHECK (bp_monitoring_schedule IN ('morning_evening', 'morning_only', 'evening_only', 'custom')),
  CONSTRAINT ck_ps_weight_unit CHECK (weight_unit IN ('kg', 'lb')),
  CONSTRAINT ck_ps_height_unit CHECK (height_unit IN ('cm', 'ft_in')),
  CONSTRAINT ck_ps_distance_unit CHECK (distance_unit IN ('km', 'miles')),
  CONSTRAINT ck_ps_language CHECK (preferred_language IN ('hi', 'en', 'bilingual'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS medical_conditions (
  id             CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id     CHAR(36) CHARACTER SET ascii NOT NULL,
  condition_name VARCHAR(255) NOT NULL,
  diagnosed_year INT NULL,
  notes          TEXT NULL,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_medical_conditions_patient (patient_id),
  CONSTRAINT fk_mc_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT ck_mc_year CHECK (diagnosed_year IS NULL OR (diagnosed_year >= 1900 AND diagnosed_year <= 2100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS medicines (
  id             CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id     CHAR(36) CHARACTER SET ascii NOT NULL,
  medicine_name  VARCHAR(255) NOT NULL,
  dose           VARCHAR(120) NOT NULL,
  scheduled_time TIME NOT NULL,
  meal_relation  VARCHAR(60) NULL,
  frequency      VARCHAR(40) NOT NULL DEFAULT 'daily',
  active         TINYINT(1) NOT NULL DEFAULT 1,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_medicines_patient_active (patient_id, active),
  CONSTRAINT fk_medicines_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- 3. Food catalogue, favourites, food log
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS food_items (
  id                 CHAR(36) CHARACTER SET ascii NOT NULL,
  name               VARCHAR(255) NOT NULL,
  name_hi            VARCHAR(255) NULL,
  category           VARCHAR(120) NOT NULL,
  subcategory        VARCHAR(120) NULL,
  reference_weight_g DECIMAL(10,3) NOT NULL DEFAULT 100,
  reference_unit     VARCHAR(30) NOT NULL DEFAULT 'g',
  calories_per_100g  DECIMAL(12,4) NULL,
  protein_g_100g     DECIMAL(12,4) NOT NULL DEFAULT 0,
  carbs_g_100g       DECIMAL(12,4) NOT NULL DEFAULT 0,
  fat_g_100g         DECIMAL(12,4) NOT NULL DEFAULT 0,
  fibre_g_100g       DECIMAL(12,4) NOT NULL DEFAULT 0,
  sodium_mg_100g     DECIMAL(12,4) NULL DEFAULT 0,
  source_type        VARCHAR(40) NOT NULL DEFAULT 'base_dataset',
  source_name        VARCHAR(255) NULL,
  source_note        TEXT NULL,
  is_verified        TINYINT(1) NOT NULL DEFAULT 1,
  is_custom          TINYINT(1) NOT NULL DEFAULT 0,
  is_active          TINYINT(1) NOT NULL DEFAULT 1,
  created_by         CHAR(36) CHARACTER SET ascii NULL,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_food_items_name (name),
  KEY idx_food_items_name_hi (name_hi),
  KEY idx_food_items_custom (is_custom, is_active),
  CONSTRAINT fk_food_items_creator FOREIGN KEY (created_by) REFERENCES auth_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS food_portions (
  id                 CHAR(36) CHARACTER SET ascii NOT NULL,
  food_item_id       CHAR(36) CHARACTER SET ascii NOT NULL,
  portion_name       VARCHAR(120) NOT NULL,
  portion_name_hi    VARCHAR(120) NULL,
  standardized_grams DECIMAL(10,3) NOT NULL,
  notes              TEXT NULL,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_food_portions_item (food_item_id),
  CONSTRAINT fk_food_portions_item FOREIGN KEY (food_item_id) REFERENCES food_items (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS patient_food_favorites (
  id           CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id   CHAR(36) CHARACTER SET ascii NOT NULL,
  food_item_id CHAR(36) CHARACTER SET ascii NOT NULL,
  created_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_patient_food_favorite (patient_id, food_item_id),
  KEY idx_pff_food (food_item_id),
  CONSTRAINT fk_pff_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT fk_pff_food FOREIGN KEY (food_item_id) REFERENCES food_items (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS food_logs (
  id                 CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id         CHAR(36) CHARACTER SET ascii NOT NULL,
  food_item_id       CHAR(36) CHARACTER SET ascii NULL,
  meal_type          VARCHAR(30) NOT NULL,
  food_name          VARCHAR(255) NOT NULL,
  quantity           DECIMAL(12,3) NOT NULL,
  unit               VARCHAR(60) NOT NULL,
  standardized_grams DECIMAL(12,3) NULL,
  calories           DECIMAL(12,3) NOT NULL,
  protein_g          DECIMAL(12,3) NOT NULL DEFAULT 0,
  carbs_g            DECIMAL(12,3) NOT NULL DEFAULT 0,
  fat_g              DECIMAL(12,3) NOT NULL DEFAULT 0,
  fibre_g            DECIMAL(12,3) NOT NULL DEFAULT 0,
  sodium_mg          DECIMAL(12,3) NULL,
  oil_quantity       VARCHAR(30) NOT NULL DEFAULT 'None',
  oil_calories       DECIMAL(12,3) NOT NULL DEFAULT 0,
  calorie_confidence VARCHAR(10) NOT NULL DEFAULT 'Medium',
  source_type        VARCHAR(40) NOT NULL DEFAULT 'base_dataset',
  source_note        TEXT NULL,
  consumed_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  notes              TEXT NULL,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_food_logs_patient_consumed (patient_id, consumed_at),
  KEY idx_food_logs_food (food_item_id),
  CONSTRAINT fk_food_logs_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT fk_food_logs_food FOREIGN KEY (food_item_id) REFERENCES food_items (id) ON DELETE SET NULL,
  CONSTRAINT ck_food_logs_quantity CHECK (quantity > 0),
  CONSTRAINT ck_food_logs_calories CHECK (calories >= 0),
  CONSTRAINT ck_food_logs_confidence CHECK (calorie_confidence IN ('High', 'Medium', 'Low'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- 4. Vitals, activity, sleep, medicines taken, checklist
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bp_logs (
  id           CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id   CHAR(36) CHARACTER SET ascii NOT NULL,
  systolic     INT NOT NULL,
  diastolic    INT NOT NULL,
  pulse        INT NULL,
  reading_type VARCHAR(40) NULL,
  measured_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  notes        TEXT NULL,
  created_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_bp_logs_patient_measured (patient_id, measured_at),
  CONSTRAINT fk_bp_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT ck_bp_systolic CHECK (systolic > 40 AND systolic < 300),
  CONSTRAINT ck_bp_diastolic CHECK (diastolic > 20 AND diastolic < 200),
  CONSTRAINT ck_bp_pulse CHECK (pulse IS NULL OR (pulse > 30 AND pulse < 250))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS weight_logs (
  id          CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id  CHAR(36) CHARACTER SET ascii NOT NULL,
  weight_kg   DECIMAL(6,2) NOT NULL,
  measured_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  notes       TEXT NULL,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_weight_logs_patient_measured (patient_id, measured_at),
  CONSTRAINT fk_weight_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT ck_weight_kg CHECK (weight_kg > 0 AND weight_kg < 500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_logs (
  id                        CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id                CHAR(36) CHARACTER SET ascii NOT NULL,
  date                      DATE NOT NULL,
  steps                     INT NOT NULL DEFAULT 0,
  distance_km               DECIMAL(10,3) NOT NULL DEFAULT 0,
  walking_minutes           INT NOT NULL DEFAULT 0,
  estimated_calories_burned DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at                DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_patient_activity_date (patient_id, date),
  CONSTRAINT fk_activity_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT ck_activity_steps CHECK (steps >= 0),
  CONSTRAINT ck_activity_distance CHECK (distance_km >= 0),
  CONSTRAINT ck_activity_minutes CHECK (walking_minutes >= 0),
  CONSTRAINT ck_activity_burned CHECK (estimated_calories_burned >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sleep_logs (
  id          CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id  CHAR(36) CHARACTER SET ascii NOT NULL,
  date        DATE NOT NULL,
  sleep_hours DECIMAL(5,2) NOT NULL,
  bedtime     TIME NULL,
  wake_time   TIME NULL,
  notes       TEXT NULL,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_patient_sleep_date (patient_id, date),
  CONSTRAINT fk_sleep_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT ck_sleep_hours CHECK (sleep_hours >= 0 AND sleep_hours <= 24)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS medicine_logs (
  id             CHAR(36) CHARACTER SET ascii NOT NULL,
  medicine_id    CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id     CHAR(36) CHARACTER SET ascii NOT NULL,
  scheduled_time DATETIME(3) NOT NULL,
  taken_time     DATETIME(3) NULL,
  status         VARCHAR(10) NOT NULL,
  notes          TEXT NULL,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_medicine_logs_patient_scheduled (patient_id, scheduled_time),
  KEY idx_medicine_logs_medicine (medicine_id),
  CONSTRAINT fk_ml_medicine FOREIGN KEY (medicine_id) REFERENCES medicines (id) ON DELETE CASCADE,
  CONSTRAINT fk_ml_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT ck_ml_status CHECK (status IN ('taken', 'late', 'missed', 'pending'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS daily_checklists (
  id             CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id     CHAR(36) CHARACTER SET ascii NOT NULL,
  checklist_date DATE NOT NULL,
  item_key       VARCHAR(80) NOT NULL,
  item_label     VARCHAR(255) NOT NULL,
  scheduled_time TIME NULL,
  status         VARCHAR(10) NOT NULL DEFAULT 'pending',
  completed_at   DATETIME(3) NULL,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_patient_checklist_item_date (patient_id, checklist_date, item_key),
  CONSTRAINT fk_dc_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT ck_dc_status CHECK (status IN ('completed', 'pending', 'late', 'missed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- 5. Caregiver invites (short-lived codes, created and redeemed server-side only)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS caregiver_invites (
  id          CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id  CHAR(36) CHARACTER SET ascii NOT NULL,
  created_by  CHAR(36) CHARACTER SET ascii NOT NULL,
  role        VARCHAR(10) NOT NULL DEFAULT 'viewer',
  code        VARCHAR(16) CHARACTER SET ascii NOT NULL,
  status      VARCHAR(10) NOT NULL DEFAULT 'pending',
  expires_at  DATETIME(3) NOT NULL,
  accepted_by CHAR(36) CHARACTER SET ascii NULL,
  accepted_at DATETIME(3) NULL,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_caregiver_invites_code (code),
  KEY idx_caregiver_invites_patient (patient_id, status),
  CONSTRAINT fk_ci_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT fk_ci_creator FOREIGN KEY (created_by) REFERENCES auth_users (id) ON DELETE CASCADE,
  CONSTRAINT fk_ci_acceptor FOREIGN KEY (accepted_by) REFERENCES auth_users (id) ON DELETE SET NULL,
  CONSTRAINT ck_ci_role CHECK (role IN ('editor', 'viewer')),
  CONSTRAINT ck_ci_status CHECK (status IN ('pending', 'accepted', 'expired', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS caregiver_invite_attempts (
  id           BIGINT NOT NULL AUTO_INCREMENT,
  user_id      CHAR(36) CHARACTER SET ascii NOT NULL,
  attempted_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_invite_attempts_user (user_id, attempted_at),
  CONSTRAINT fk_cia_user FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- 6. SOIE ("Ask"): conversations, feedback, telemetry, family memories
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS soie_sessions (
  id             CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id        CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id     CHAR(36) CHARACTER SET ascii NOT NULL,
  title          VARCHAR(255) NULL,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_active_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_soie_sessions_user (user_id, last_active_at),
  KEY idx_soie_sessions_patient (patient_id),
  CONSTRAINT fk_ss_user FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE,
  CONSTRAINT fk_ss_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS soie_messages (
  id         CHAR(36) CHARACTER SET ascii NOT NULL,
  session_id CHAR(36) CHARACTER SET ascii NOT NULL,
  role       VARCHAR(10) NOT NULL,
  content    TEXT NOT NULL,
  answer     JSON NULL,
  model      VARCHAR(120) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_soie_messages_session (session_id, created_at),
  CONSTRAINT fk_sm_session FOREIGN KEY (session_id) REFERENCES soie_sessions (id) ON DELETE CASCADE,
  CONSTRAINT ck_sm_role CHECK (role IN ('user', 'assistant'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS soie_feedback (
  id         CHAR(36) CHARACTER SET ascii NOT NULL,
  message_id CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id    CHAR(36) CHARACTER SET ascii NOT NULL,
  rating     VARCHAR(12) NOT NULL,
  comment    TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_soie_feedback (message_id, user_id),
  KEY idx_soie_feedback_user (user_id),
  CONSTRAINT fk_sf_message FOREIGN KEY (message_id) REFERENCES soie_messages (id) ON DELETE CASCADE,
  CONSTRAINT fk_sf_user FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE,
  CONSTRAINT ck_sf_rating CHECK (rating IN ('helpful', 'not_helpful'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS soie_events (
  id            CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id       CHAR(36) CHARACTER SET ascii NOT NULL,
  session_id    CHAR(36) CHARACTER SET ascii NULL,
  patient_id    CHAR(36) CHARACTER SET ascii NULL,
  intent        VARCHAR(80) NULL,
  status        VARCHAR(20) NOT NULL,
  tools_used    JSON NULL,
  data_points   INT NULL,
  latency_ms    INT NULL,
  model         VARCHAR(120) NULL,
  input_tokens  INT NULL,
  output_tokens INT NULL,
  created_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_soie_events_user_time (user_id, created_at),
  CONSTRAINT fk_se_user FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE,
  CONSTRAINT fk_se_session FOREIGN KEY (session_id) REFERENCES soie_sessions (id) ON DELETE SET NULL,
  CONSTRAINT fk_se_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE SET NULL,
  CONSTRAINT ck_se_status CHECK (status IN ('success', 'refused', 'emergency', 'no_data', 'validation_failed', 'fallback', 'error', 'rate_limited'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Things the family tells SOIE to remember about the patient ("allergic to milk", ...).
CREATE TABLE IF NOT EXISTS soie_memories (
  id         CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id CHAR(36) CHARACTER SET ascii NOT NULL,
  kind       VARCHAR(12) NOT NULL,
  content    VARCHAR(500) NOT NULL,
  created_by CHAR(36) CHARACTER SET ascii NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_soie_memories_patient (patient_id, created_at),
  CONSTRAINT fk_memories_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT fk_memories_creator FOREIGN KEY (created_by) REFERENCES auth_users (id) ON DELETE SET NULL,
  CONSTRAINT ck_memories_kind CHECK (kind IN ('allergy', 'preference', 'routine', 'goal', 'note'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- A meal photo the family confirmed: the model's image embedding plus the foods that
-- were logged for it. New photos are matched against these, so the app learns the
-- family's own dishes. No photo is stored, only a 64 px thumbnail for the review list.
CREATE TABLE IF NOT EXISTS food_photo_examples (
  id          CHAR(36) CHARACTER SET ascii NOT NULL,
  patient_id  CHAR(36) CHARACTER SET ascii NOT NULL,
  meal_type   VARCHAR(30) NULL,
  foods       JSON NOT NULL,
  embedding   JSON NOT NULL,
  thumbnail   TEXT NULL,
  created_by  CHAR(36) CHARACTER SET ascii NULL,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_food_photo_examples_patient (patient_id, created_at),
  CONSTRAINT fk_fpe_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT fk_fpe_creator FOREIGN KEY (created_by) REFERENCES auth_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
